# Server
server.port=8080
spring.application.name=dcvs-backend

# Fabric Gateway Configuration
fabric.msp-id=Org1MSP
fabric.channel-name=mychannel
fabric.chaincode-name=credential
fabric.peer-endpoint=localhost:7051
fabric.peer-host-alias=peer0.org1.example.com

# Correct crypto path
fabric.crypto-path=/home/divya_shukla/DCVS_Project/blockchain/fabric-samples/test-network/organizations/peerOrganizations/org1.example.com

# TLS cert
fabric.tls-cert-path=${fabric.crypto-path}/peers/peer0.org1.example.com/tls/ca.crt

# Admin cert
fabric.cert-path=${fabric.crypto-path}/users/Admin@org1.example.com/msp/signcerts/cert.pem

# Private key directory
fabric.key-path=${fabric.crypto-path}/users/Admin@org1.example.com/msp/keystore

# Certificate settings
app.base-url=http://localhost:5173
app.issuer-name=DCVS University

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.com.dcvs=DEBUG
logging.level.org.hyperledger=INFO
